# Generated by Django 4.2.7 on 2023-12-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
